version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwordRoot
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "green-shift"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
    volumes:
      - sql-data:/var/lib/mysql
      - "./services/db/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./services/db/data.sql:/docker-entrypoint-initdb.d/2.sql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '5171:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: root
  node-api:
    container_name: api_node
    build: ./services/api
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - ./services/api:/app
    environment:
      - PORT=3000
    env_file:
      - ./services/api/.env
  node-api-v2:
    container_name: api_node_V2
    build: ./services/api_V2
    depends_on:
      - mongo
    ports:
      - "3001:3000"
    volumes:
      - ./services/api_V2:/app
    environment:
      MONGODB_URI: mongo_db://mongo:27017/Tree-api
      MANGODB_USER: root
      MANGODB_PASSWORD: passwordRoot
      PORT: 3000
  angular-service:
    container_name: angular
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
    ports: 
        - '4200:4200'

volumes:
  db-data:
  sql-data: